### ISSUE TITLE
multiple copies of explainer.md

### ISSUE THREAD

**Issue by sublimator** [interledger/webmonetization.org#10]
![image](https://user-images.githubusercontent.com/525211/66444586-f8eb0f00-ea6d-11e9-8e9e-8d6b6a4b2e23.png)

**Comment by sublimator** [comment]
#13 

We might want a script to import the explainer from https://github.com/adrianhopebailie/web-monetization/blob/master/explainer.md to keep it in sync

**Comment by adrianhopebailie** [comment]
Current plan is to migrate to this repo from adrianhopebailie/web-monetization. Will close this when we've done that
