### ISSUE TITLE
Finalized event or add finalized property on stopped event

### ISSUE THREAD

**Issue by sublimator** [interledger/webmonetization.org#39]
The [react-web-monetization](https://github.com/sharafian/react-web-monetization) library useMonetizationState state hook includes in its state, a hasPaid property which specifies if any payments have been made for the the current requestId. 

During the monetizationstopped event, the library needs to examine the document for the presence of a meta tag to determine if the monetization has completely stopped in the sense that the meta tag has been removed (edit: or the [@content] changed) and there's no way that any more packets for that requestId can be sent.

Some options would be:
1. adding a finalized: boolean property to the monetizationstopped event detail
2. adding a separate monetizationfinalized event

**Comment by sublimator** [comment]
Or of course, a 'paused' state 
Or ... multivariate state

**Comment by sharafian** [comment]
What's the criteria for `finalized`? will it be finalized if I switch the meta tag's content, or only if I remove the meta tag entirely?

**Comment by sublimator** [comment]
@sharafian 
Sorry for the late reply! 
Yeah, I believe both? Essentially the `<meta>` tag being removed or changed?

**Comment by sublimator** [comment]
Right, as per https://github.com/sharafian/react-web-monetization/blob/master/src/global.js#L95-L99
