### ISSUE TITLE
Specify support for <iframe allow="monetization"> 

### ISSUE THREAD

**Issue by sublimator** [interledger/webmonetization.org#52]
At one point we removed iframes from the spec until we had a 'sensible working implementation'
Coil extension version v47 add preliminary support for iframes which will be refined over time.
Need to update the spec (and potentially impl to match)

**Comment by Malvoz** [comment]
`allow` is defined by the Feature-Policy spec, there's already an issue to define monetization as a policy-controlled feature in https://github.com/interledger/webmonetization.org/issues/28. Not sure if it makes sense to keep this as a separate issue or merge into that?

**Comment by sublimator** [comment]
I believe @melissahenderson added some mention of the current implementation, so will close this in favor of the issue you linked (#28 )
