### ISSUE TITLE
Only Pay while stream?

### ISSUE THREAD

**Issue by SamuelEVicente** [interledger/webmonetization.org#58]
I hope this is the correct place to post this question. At Musicoin we offer users to stream music and pay the content creator immediately with smart contracts. We are looking into web monetization, we are wondering whether it’s possible to only make the user pay while streaming?

**Comment by novazembla** [comment]
You can start and stop monetization by adding or removing the meta tag (`<meta
  name="monetization"
  content="$wallet.example.com/alice">`) to/from your documents `<head>`. A change of the payment pointer should also be picked up and trigger a new payment. Thus you could change your audio player to set the meta tag on play and remove it on pause/stop.

To be able to do that you need to have access to either the root document or in case you embed an `<iframe>` it must allow monetization e.g. (`<iframe src="/wm/example.htm" width="600" height="800" allow="monetization">`) and then you can make changes to the iframe's document.. 

That said, I believe that the monetization agent/provider has quite a bit of discretion in terms if, when, and how much they are going to pay after all.

**Comment by adrianhopebailie** [comment]
@SamuelEVicente there isn't a need to stop and start really. With WM you don't "make the user pay" they simply pay all the time that they are on a monetized site. This makes the API much simpler.

As a platform you could redirect the payments depending on whether the user is streaming or not so the creator only gets paid when the content is streaming.

You could direct any other payments to the platform or charity or something like that.

**Comment by SamuelEVicente** [comment]
@adrianhopebailie @novazembla  Thank you guys for responding, it was a big help.
